backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "sermons"
    label: "설교"
    folder: "content/sermons"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "날짜", name: "date", widget: "datetime"}
      - {label: "본문", name: "body", widget: "markdown"}
      - {label: "동영상 링크", name: "video", widget: "string"}
